!/bin/env python
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 28 13:40:43 2016

@author: Ryan Swope - Evolve IP
"""
import sys, csv, re, os

DIR = os.path.dirname(os.path.realpath(__file__))
regex = re.compile("\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}")
input_file = sys.stdin.readlines() #handles stdin
input_list = []
pairing_dict = {}

for i in input_file:
    input_list.append(i.rstrip()) #chomp newline chars from input_file

if len(sys.argv) > 1: #if argument is given after .py file, becomes ip lookup
    ip_lookup = sys.argv[1]
else:
    ip_lookup = DIR + "/List-Of-IPs.csv"  #default if nothing is given

with open(ip_lookup, 'rb') as csvfile:
    filereader = csv.reader(csvfile)
    for row in filereader:
        temp=(str.split((','.join(row)), ','))
        #temp is assigned to list generated by split method with host/ip pair
        pairing_dict[temp[1]] = temp[0]
        #populates dictionary, ips are keys and hosts are values

for line in input_list:
    words = line.split() #for multiple ips on one line, split
    output = [] #used for initializing AND clearing list
    for ip in words:
        test = regex.match(ip)
        if test:
            stripped_ip = regex.search(ip).group() #strips ip of attached stuff
            if stripped_ip in pairing_dict:
                host = pairing_dict[stripped_ip]
                output.append(ip.replace(stripped_ip,host))
            else:
                output.append(ip) #returns ip as is if not found in csv file
        else:
            #This is hit when there is not a match based on the IP
            output.append(ip)
    print(' '.join(output))
